SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) AS AVERAGE_DURATION -- DATEDIFF()는 0이 있다는 것을 생각하기
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID 
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC ; -- 항상 문제 볼 때 내림차순 소홀히 하는 경향이 있어서 주의
