SELECT HISTORY_ID, CAR_ID,	DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE,	DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE ,
CASE WHEN
  DATEDIFF(END_DATE, START_DATE) >= 29 THEN '장기 대여' -- 날짜형식은 무조건 DATEDIFF 씌워주기
ELSE '단기 대여' -- ELSE는 THEN을 붙이지 않도록 주의하기
  END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) = 9 
ORDER BY HISTORY_ID DESC ;
-- 주의) DATEDIFF는 날짜의 '차이'를 나타내는 것이므로, 대여 '기간'이 30일 이상이면 29로 표기해줘야 함
