SELECT BOARD_ID, WRITER_ID,	TITLE,	PRICE,
CASE WHEN STATUS = 'SALE' THEN '판매중'
     WHEN STATUS = 'RESERVED' THEN '예약중'
     ELSE '거래완료' END
AS STATUS
FROM USED_GOODS_BOARD 
WHERE CREATED_DATE IN ('2022-10-05') -- IN은 리스트 안에 넣기
ORDER BY BOARD_ID DESC ; 
