SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B
INNER JOIN USED_GOODS_REPLY AS R -- 바로 INNER JOIN을 활용함, 문제를 읽고 LEFT JOIN을 사용하면 안되는 이유도 생각하기
ON B.BOARD_ID = R.BOARD_ID
WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
-- 대용량의 데이터인 경우, 인덱스를 타면서 빠르게 검색하기 위해 BETWEEN 고려
-- WHERE B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31 23:59:59'
ORDER BY R.CREATED_DATE, B.TITLE ;

-- 문제에서 INNER JOIN과 LEFT JOIN중 어떤 것을 선택할 지 애매하게 작성되어 있음
-- 정답 기준으로, 댓글이 없는 게시글은 조회하지 않기 위해, 여기서는 INNER JOIN으로 접근하는 것을 원하는 듯
