SELECT E.YEAR, (M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM
  (SELECT
  ID, SIZE_OF_COLONY, YEAR(DIFFERENTATION_DATE) AS YEAR
  FROM ECOLI_DATA) AS E -- 개별 대장균 정보 테이블
JOIN 
  (
  SELECT
    YEAR(DIFFERENTATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE -- GROUP BY에서 사용한 컬럼을 반드시 SELECT문에 포함
  FROM ECOLI_DATA
  GROUP BY YEAR(DIFFERENTATION_DATE)
  ) AS M -- 연도별 최대 대장균 크기 테이블
ON E.YEAR = M.YEAR
ORDER BY E.YEAR, YEAR_DEV ;

-- 인라인 뷰를 만들고, JOIN을 한 뒤 ALIAS를 붙이고 이후에 SELECT에 사용할 수 있음
-- 인라인 뷰 내부에서 ALIAS 사용하는 것이 아님을 인지하기
