SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT ) ; -- 최고가가 여러개 있을 때 중복허용

-- MAX : '집계함수'이므로 서브쿼리나 GROUP BY 함수 없이 다른 컬럼과 같이 사용하는 경우 오류 발생
-- 위에서는 SELECT에 PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, MAX(PRICE)를 사용하면 오류

-- 중복 허용하지 않은 풀이
SELECT *
FROM FOOD_PRODUCT
ORDER BY PRICE DESC 
LIMIT 1 ;
